- ros_topic_name: "/clock" # global ns
  gz_topic_name: "/world/spawner_world/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS  # BIDIRECTIONAL or ROS_TO_GZ

- ros_topic_name: "/tf"
  gz_topic_name: "model/cuboid/pose"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS
